### PR TITLE
Arm64 bindings

### PR DESCRIPTION
**Pull request by konistehrad**
Depends on https://github.com/mono/CppSharp/pull/1824. Expands bindings to include ARM64 for Linux and Mac, and updates Mac headers to 12.3 to allow for ARM64 usage.

Uses the following updated header package:  [headers.zip](https://github.com/mono/CppSharp/files/14151916/headers.zip)

### CODE REVIEW

**Comment by konistehrad** [comment]
Sorry, meant to open as draft. I made a pretty silly mistake in the MacOS headers that I'll have to correct tomorrow. Would love some eyes on the linux side in the meantime tho.

**Comment by konistehrad** [comment]
Took a crack at resolving the errors this morning to no avail. Updated the headers package with a clean version. Might help to have someone more familiar with the project take a swing at resolving the segfaults on ARM64 Mac.

**Comment by konistehrad** [comment]
So the state of play:

-I don't think an ARM64 host is building LLVM. I'm still having to build it locally to work.
-My Debian VM fails to complete the LLVM build, so I'm having a hard time testing ARM64 on Linux.
-Mac gets segmentation faults during the final build step. Looks like one of the bindings might be incorrect somehow?

**Comment by konistehrad** [comment]
That's interesting, because attempting to use the generated `llvm-6eb36a-linux-arm64-gcc-11-Release` yields a bunch of these when attempting to build on Linux ARM64:

`/usr/bin/ld: skipping incompatible ../../llvm/llvm-6eb36a-linux-arm64-gcc-11-Release/build/lib/libLLVMDebugInfoPDB.a when searching for -lLLVMDebugInfoPDB
/usr/bin/ld: cannot find -lLLVMDebugInfoPDB: No such file or directory`

Archive files are a little harder to inspect than shared libs, but I'm used to seeing this error when the generated archive contains the wrong architecture.

**Comment by konistehrad** [comment]
Gotcha. Let me cook up some cmake toolchain files to do the LLVM cross compile anyway. That’d save me a ton of time. I’ll make that in a different branch to expedite review and we can kick off a new LLVM job.

**Comment by konistehrad** [comment]
Actually, while I have you: what's the correct way to determine host architecture in premake? I can't seem to find a way to test to see if we're executing on an x64 host for an arm64 target.

**Comment by konistehrad** [comment]
Oh, yes, I did find `os.host()`, unfortunately it doesn't seem to return architecture info. For example, from an M1 Mac in interactive mode:

```
> print(os.host())
macosx
```

Not quite enough to do the dirty work I'm afraid. I guess I can use `uname` on this path since our cross compile paths are limited to Unix-like operating systems.

**Comment by konistehrad** [comment]
OK, state of play:

- Rosetta context wasn't a good enough test bed for ARM64 cross compiling. I'll need help from someone with access to a real Intel Mac to smooth that out it looks like.
- I updated the Calling Convention from Cdecl to Winapi in `std.cs` for ARM Mac and it appears to have cleaned some stuff up. It's failing to find some libraries now, but it's progress.
- It looks like we need to add Arm64 to `src/CppParser/AST.h`, but I don't know yet where else this needs to end up. I'll be working on that as able.

**Comment by konistehrad** [comment]
Sorry, I'm not able to continue working on this due to some major life stuff. I'll close it for now. If anyone else wants to pick up the effort just ping me and I'll try to help as able.

**Comment by perlun** [comment]
For reference, trying to get this moving now here: https://github.com/mono/CppSharp/issues/1708#issuecomment-3866466584

**Pull request closed without merging**
