### PR TITLE
Fix wrong generated destructor

### LINKED ISSUE #1419: Generated std::string destructor is wrong when target is i686-pc-win32-msvc
The parameter `deleted` should be removed.

OS: Windows

##### Used settings

`Driver.ParserOptions.TargetTriple = "i686-pc-win32-msvc"`

Target: MSVC

##### Stack trace or incompilable generated code

```.cs
[SuppressUnmanagedCodeSecurity]
[DllImport("Std-symbols", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.ThisCall,
    EntryPoint="??1?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@QAE@XZ")]
internal static extern void dtorc__N_std_S_basic_string__C___N_std_S_char_traits__C___N_std_S_allocator__C
    (global::System.IntPtr __instance, int deleted); 

global::Std.BasicString.__Internalc__N_std_S_basic_string__C___N_std_S_char_traits__C___N_std_S_allocator__C.dtorc__N_std_S_basic_string__C___N_std_S_char_traits__C___N_std_S_allocator__C
       (__Instance, 0);
```

### PR DESCRIPTION
**Pull request by josetr**
Fixes #1419

### CODE REVIEW

**Comment by ddobrev** [comment]
@josetr while I trust this fix works are you sure it is correct? These hidden parameters are strictly defined by the ABI. In fact, we've had for quite some time the idea of reading these from Clang instead of writing them ourselves based on ms's scattered documentation on the subject. This would need to happen somewhere around https://github.com/mono/CppSharp/blob/master/src/CppParser/Parser.cpp#L3301 as the info about code generation contains these ABI parameters if any.

**Comment by josetr** [comment]
@ddobrev No, I can't be sure due to lack of documentation like you said. The target i686-pc-win32-msvc certainly needs it since my other 2 pull requests (and my library that is using CppSharp) fail every time without it.

Maybe the Microsoft 64bit ABI doesn't need the `IsVirtual` check, but I highly doubt it. The memory corruption for the 32 bit target was silent and just doesn't show until your library gets complex enough to trigger it. The same is probably happening for the 64 bit target.

**Comment by ddobrev** [comment]
@tritao what do you think?

**Comment by tritao** [comment]
Fix looks correct to me, deleted destructors should always be virtual.

**Comment by ddobrev** [comment]
@josetr it's possible that you've fixed part of the problem with this PR but [not all of it](https://ci.appveyor.com/project/tritao/cppsharp/builds/35874369/job/1agpg1krqegspps3#L1017). I cannot tell if it's related to this kind of hidden parameters but the only reliable way to get them correctly is reading them from Clang as I mentioned [earlier](https://github.com/mono/CppSharp/pull/1429#issuecomment-710779337). If you feel you could give it a try, I'm definitely available to help.

**Comment by josetr** [comment]
@ddobrev I already saw this same test breaking CI build failing before so I've managed to reproduce the issue and it seems the code generated to copy a string is still wrong so the problem may be related to #1420 instead.

**Pull request merged**
