### PR TITLE
 Fixed a problem when walking the managed AST because friend templated  classes were seen as declared multiple times and resulted into a crash

### PR DESCRIPTION
**Pull request by zillemarco**

### CODE REVIEW

**Comment by zillemarco** [comment]
@ddobrev should be ok now

**Comment by zillemarco** [comment]
Sorry, I read your message completely after my last comment. Is it ok like I did it?

**Comment by tritao** [comment]
Thanks

**Comment by zillemarco** [comment]
You're welcome

**Comment by ddobrev** [comment]
@zillemarco yours is too long and I would've preferred mine. But much better than the other way around and besides @tritao 's already merged it.

**Comment by zillemarco** [comment]
@ddobrev agreed, that's too long. My mistake sorry

**Pull request merged**
