### PR TITLE
Handle pointer to pointer param

### PR DESCRIPTION
**Pull request by IIFE**

### CODE REVIEW

**Comment by ddobrev** [comment]
@IIFE I've merged one of your PR-s and there conflicts now, please resolve.

**Comment by IIFE** [comment]
@ddobrev Update this branch. Can you please merge it and I'll update the subsequent PRs.

**Comment by ddobrev** [comment]
@IIFE better now but please try moving the test to `Common` again. If it works for you locally, I'd rather have it there.

**Comment by IIFE** [comment]
@ddobrev You mean move it so that it's generated for both CLI and C#?

**Comment by ddobrev** [comment]
Precisely.

**Comment by IIFE** [comment]
@ddobrev Done.

**Pull request merged**
