### PR TITLE
Allow the users to overwrite CppSharp type maps.

### PR DESCRIPTION
**Pull request by fsinisi90**

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/mono/CppSharp?pullRequest=1401) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/mono/CppSharp?pullRequest=1401) before we can accept your contribution.<br/><br/>:x: fsinisi90 [sign now](https://cla.dotnetfoundation.org/mono/CppSharp?pullRequest=1401)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/mono/CppSharp?pullRequest=1401) it.</sub>

**Comment by tritao** [comment]
This PR has some extra commits that were already merged before (the documentation one).

Can you get rid of it by rebasing this work on top of master?

**Comment by fsinisi90** [comment]
I've just synced the original repository to my fork and the duplicated changes were gone. You'll notice that there is still a change in which I've removed a word and that was pushed along with this new feature. If that's a problem I can remove it, I've just thought that it didn't hurt to add that small cosmetic change as well. Just let me know.

**Comment by tritao** [comment]
Yeah that's fine.

But unfortunately your latest push made things worse, now there is an extra merge commit on top of what was there before.

You should create a new branch on top of latest master, then cherry-pick your commit `994b95c6cc2a11df9938de384c48ee0411a07c20` on top. And force push to your PR branch.

That should fix things, and end up with a single commit on the commits tab above.

**Comment by ddobrev** [comment]
@fsinisi90 in addition, I don't want deliberately causing exceptions and catching them in empty blocks as at https://github.com/mono/CppSharp/commit/2e5db1ae8218eec260357efa200f39976e81cf03#diff-3b1430b7dc2a290aada959006eb9c36dR50. If you don't want to replace type maps, use `Contains`.

**Comment by tritao** [comment]
Hey @fsinisi90 can you rebase this? Would like to get this merged.

**Comment by fsinisi90** [comment]
@tritao Definitely. I'll do it with the changes proposed by @ddobrev over the weekend.

**Pull request closed without merging**
