### PR TITLE
Fixing printing of comments for C#

### PR DESCRIPTION
**Pull request by realvictorprm**
Signed-off-by: realvictorprm <mueller.vpr@gmail.com>

### CODE REVIEW

**Comment by realvictorprm** [comment]
This is much better in my opinion. I don't understand why we used `<param>` always before.

**Comment by tritao** [comment]
I think the `<param>` stuff is to force VS to break new lines when showing Intellisense tooltips. @ddobrev will know better.

**Comment by realvictorprm** [comment]
@tritao Need to check this again, however we finally have no remarks anymore where summaries should be.

**Comment by realvictorprm** [comment]
@tritao yes para forces intellisense to use a newline ... hm let's remove at least this change.

**Comment by realvictorprm** [comment]
I need to go over this again

**Pull request closed without merging**
