### PR TITLE
Marshal all char ptrs to StringBuilder

### PR DESCRIPTION
**Pull request by genuinelucifer**
Build is failing currently. I'm trying to fix it.

### CODE REVIEW

**Comment by ddobrev** [comment]
Great to see you working again, I am sure you'll overcome it this time.

**Comment by genuinelucifer** [comment]
Thanks. I hope too that this time i would be able to complete it.

**Comment by genuinelucifer** [comment]
@ddobrev It builds correctly on my windows pc and tests do run too. I don't know what's going wrong on the Mac buildbot!
I'm looking into it.
Meanwhile, I was trying to marshal the constant sized value type arrays too but it seems then we can't take pointer to ```Internal``` struct if it has any managed type and fixing that seemed to be quite large task. I couldn't think of any other solution so I dropped that idea and left my temporary solutions as permanent ones. If it is acceptable to change the types by comparing and checking equality to ```StringBuilder``` at the 2 places then I'll leave it else I will try to do something else.

**Comment by ddobrev** [comment]
Thank you for your work. if you have problems with the arrays, please leave them for now, pointers are fine as a start. About the crash on Unix, searching yields quite a few results (https://www.google.bg/search?q=Structure+field+of+type+Char[]+can%27t+be+marshalled+as+LPArray&ie=utf-8&oe=utf-8&gws_rd=cr&ei=OsmsVuuqJIqasAGJyLTIBA#q=%22Structure+field+of+type%22+%22can%27t+be+marshalled+as+LPArray%22), it might be helpful. I'll discuss it with @tritao a little later.

**Comment by genuinelucifer** [comment]
I tried those things already. Actually those define for Marshalling fields
which i haven't incorporated yet.

**Comment by ddobrev** [comment]
@tritao do you have any clue about the crash at the Unix builds?

**Comment by genuinelucifer** [comment]
@ddobrev Although i'll try to resolve the issues in this pull. But, please give me some other task to work  on untill we find a solution for this.

**Comment by ddobrev** [comment]
@genuinelucifer my apologies, both @tritao and I have been really busy lately. Another issue you could try is https://github.com/mono/CppSharp/issues/435 .

**Comment by tritao** [comment]
After careful deliberation and discussion between me and @ddobrev, I have decided that this approach is not the best design for this feature since it will not work in a lot of cases we would like to support. We'll eventually come up with a better proposal for the new design.

**Pull request closed without merging**
