### PR TITLE
Added parameter index to managed marshal variables

### PR DESCRIPTION
**Pull request by mattparks**
Fix for issue https://github.com/mono/CppSharp/issues/1096

### CODE REVIEW

**Comment by tritao** [comment]
The code as-is does not compile, we also need a new test-case for this issue to merge the fix.

**Comment by mattparks** [comment]
So I fixed the build error, what test do you think this should be added into?

**Comment by tritao** [comment]
Try here in `ImplementsVirtualFunctionsWithStringParams `.

https://github.com/mono/CppSharp/blob/master/tests/Common/Common.h#L1340
https://github.com/mono/CppSharp/blob/master/tests/Common/Common.cpp#L896
https://github.com/mono/CppSharp/blob/master/tests/Common/Common.Tests.cs#L803

**Comment by mattparks** [comment]
Ok added tests for this into `ImplementsVirtualFunctionsWithStringParams`, appears to have worked properly.

**Comment by tritao** [comment]
👍

**Pull request merged**
