### PR TITLE
Embedded array of struct issues. Resolves mono/CppSharp#1598

### PR DESCRIPTION
**Pull request by jpnoir**
See issue #1598 for description.

### CODE REVIEW

**Comment by tritao** [comment]
Thanks for the fixes, it looks good.

The Windows CI with some Nuget issues, I've re-run all jobs in the meanwhile to see if it was just some temporary thing.

**Comment by jpnoir** [comment]
Thanks, I have no idea why the restores (NUnit, etc.) are failing on the windows side. I didn’t change anything there and they obviously worked locally.

**Comment by tritao** [comment]
Even though the PR CI was fully green, master is now complaining: https://github.com/mono/CppSharp/runs/2350856410#step:6:11

I am not sure why and don't really have time to check this right now.

If you got time to check this, it would be appreciated.

**Comment by jpnoir** [comment]
I don't understand it either. The message(s) indicate some sort of CI-time SDK configuration error. 

I tried pulling the newly merged main branch and (of course) had no trouble restoring / building locally.

The projects that are failing are all C++/CLI projects which seems to match the docs pointed to by the URL in the error message. I haven't yet found where Visual Studio / MS Build establishes the expected AppHost version. However, if I'm interepreting the error message correctly, the version it found is (3.1.14). That version is included in the latest VS2019 version, v16.9.4. The previous Visual Studio version (v16.9.3) uses 3.1.13. The doc that the URL in the message refers you to suggests that scenario might be the issue: 

>  "This is typically caused by having a newer SDK than the one included in Visual Studio for C++/CLI projects. "

I can't see any version info for Visual Studio in the logs. Could this be the problem? Is it possible to update Visual Studio on the CI server?

**Pull request merged**
