### PR TITLE
Added support for the constant array

### PR DESCRIPTION
**Pull request by ebifrier**
I added the static variables for tests, but in this case export comes need to '__declspec(dllimport)'.
And this patch doesn't pass tests for csharp.

I a bit confused, so I reopen a pull request.
I will check how to use git, and 'force-push'.
Thank you for @tritao.

### CODE REVIEW

**Comment by tritao** [comment]
Could you rebase this?

**Comment by ebifrier** [comment]
I rebased, but it looks like a chaos.
Does force-push save me ?
Or should I close this pull-request ?

**Comment by tritao** [comment]
Do need to close it, just rebase locally and then force-push to your pull request branch.

**Comment by tritao** [comment]
Hey, I'd like to merge this one, could you rebase your work on top of master?

**Pull request closed without merging**
