### PR TITLE
Marshal non primitive fixed arrays.

### PR DESCRIPTION
**Pull request by IIFE**
Non primitive arrays are not being marshalled correctly for C++/CLI.

### CODE REVIEW

**Comment by ddobrev** [comment]
@IIFE thank you for adding a test too but may I ask you to also extend your test to the run-time too? That is, add a unit test which reads from and writes to the generated array.
Please do not send the test in a new commit but rather amend and force-push.

**Comment by IIFE** [comment]
@ddobrev What project do I need to use to add unit tests that test generated code?

**Comment by ddobrev** [comment]
`Common.Tests.cs`

**Comment by IIFE** [comment]
Is it possible to run the tests locally on Windows?

**Comment by ddobrev** [comment]
@IIFE yes, with any NUnit test runner.

**Comment by tritao** [comment]
Regarding Travis, it's hit by a failure that happens once in a while, you can safely ignore it.

**Comment by IIFE** [comment]
@ddobrev @tritao Test added. Thanks.

**Comment by tritao** [comment]
Thanks, Travis now has a real failure:

```
1) Error : CommonTests.TestNonPrimitiveFixedArrays
System.EntryPointNotFoundException : _ZN16NonPrimitiveType6GetFooEv
```

You need to move the `GetFoo` method definition to the source file (`.cpp`).

**Comment by ddobrev** [comment]
@IIFE one final change, please: move the implementations of your functions to *.cpp. When functions are defined in the header, they're sometimes inlined and the work to handle such is ongoing.

**Comment by IIFE** [comment]
@ddobrev @tritao Done.

**Pull request merged**
